spring.application.name=serivceMaker
spring.datasource.url=jdbc:postgresql://localhost:5432/servicemaker
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver