spring.application.name=serivceMaker
spring.datasource.url=jdbc:postgresql://autorack.proxy.rlwy.net:44626/railway
spring.datasource.username=postgres
spring.datasource.password=VkSHVJkKYqUAopijrQfXuNeAYnkygFLT
spring.datasource.driver-class-name=org.postgresql.Driver
api.security.token.secret=${JWT_SECRET:my-secret-key}
spring.jpa.show-sql=true
