spring.application.name=serivceMaker
spring.datasource.url=jdbc:postgresql://localhost:5432/servicemaker
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
api.security.token.secret=${JWT_SECRET:my-secret-key}
spring.jpa.show-sql=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vrpmichels@gmail.com
spring.mail.password=pkgc onez sgtl tyne
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true